/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Clases.Alquilervehiculos;
import java.awt.SystemColor;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.border.LineBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class FrmAdministracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    String ContratoArrendamiento, NombreArrendador, CedulaArrendador,
            DireccionArrendario, NombreArrendatario, CedulaArrendatario, PlacaVehiculo;
    int ValorContrato, PagoMensual, FormaDePago;
    ArrayList<Alquilervehiculos> listaAlquiler;
    String[] encabezado = {"Documento Arrendador", "Arrendador", "Direccion", "Placa", "Arrendatario", "Documento Arrendatario", "Tiempo", "Metodo"};

    public FrmAdministracion() {
        initComponents();
        llenarTiempoContratoComboBox();
        llenarMetodoPagoComboBox();
        listaAlquiler = new ArrayList();
        MostrarInfor(listaAlquiler);
    }

    private void llenarTiempoContratoComboBox() {
        ArrayList<String> opcionesTiempo = new ArrayList<>();
        opcionesTiempo.add("1 año");
        opcionesTiempo.add("3 años");
        opcionesTiempo.add("5 años");
        DefaultComboBoxModel<String> modeloComboTiempo = new DefaultComboBoxModel<>();
        for (String opcion : opcionesTiempo) {
            modeloComboTiempo.addElement(opcion);
        }
        TiempoContratoComboBox.setModel(modeloComboTiempo);
    }

    private void llenarMetodoPagoComboBox() {
        ArrayList<String> opcionesPago = new ArrayList<>();
        opcionesPago.add("Efectivo");
        opcionesPago.add("Transferencia");
        DefaultComboBoxModel<String> modeloComboPago = new DefaultComboBoxModel<>(opcionesPago.toArray(new String[opcionesPago.size()]));
        MetodoDePagoComboBox.setModel(modeloComboPago);
    }

    public void MostrarInfor(ArrayList<Alquilervehiculos> alquiler) {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.setColumnIdentifiers(encabezado);
        for (int i = 0; i < alquiler.size(); i++) {
            modelo.addRow(new Object[]{
                alquiler.get(i).getCedulaArrendador(),
                alquiler.get(i).getNombreArrendador(),
                alquiler.get(i).getDireccionArrendatario(),
                alquiler.get(i).getPlacaVehiculo(),
                alquiler.get(i).getNombreArrendatario(),
                alquiler.get(i).getCedulaArrendatario(),
                alquiler.get(i).getTiempoContrato(),
                alquiler.get(i).getFormaDePago(),});
        }
        tableListaAlquiler.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nArrendador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cArrendador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dcArrendador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        plVehiculo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        nArrendatario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cArrendatario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TiempoContratoComboBox = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        MetodoDePagoComboBox = new javax.swing.JComboBox<>();
        BotonRegistrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListaAlquiler = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Contrato");

        jLabel2.setText("Nombre Arrendador ");

        jLabel3.setText("Cedula Arrendador");

        jLabel4.setText("Direccion Arrendador");

        jLabel5.setText("Placa Vehiculo");

        jLabel6.setText("Nombre Arrendatario");

        jLabel7.setText("Cedula Arrendatario");

        jLabel8.setText("Tiempo del Contrato");

        TiempoContratoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel9.setText("Metodo de Pago");

        MetodoDePagoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotonRegistrar.setText("Registrar");
        BotonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRegistrarActionPerformed(evt);
            }
        });

        tableListaAlquiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableListaAlquiler);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(nArrendador, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cArrendador, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nArrendatario))
                    .addComponent(TiempoContratoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(MetodoDePagoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cArrendatario, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(plVehiculo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(dcArrendador, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(92, 92, 92)
                        .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nArrendador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nArrendatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cArrendador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cArrendatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dcArrendador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TiempoContratoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(plVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MetodoDePagoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(BotonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRegistrarActionPerformed
        // TODO add your handling code here:
        if (!nArrendador.getText().isBlank() && !cArrendador.getText().isBlank() && !dcArrendador.getText().isBlank() && !plVehiculo.getText().isBlank() && !nArrendatario.getText().isBlank() && !cArrendatario.getText().isBlank()) {
            Alquilervehiculos newalquiler = new Alquilervehiculos(nArrendador.getText(), cArrendador.getText(), dcArrendador.getText(), nArrendatario.getText(), cArrendatario.getText(), plVehiculo.getText(), TiempoContratoComboBox.getItemAt(TiempoContratoComboBox.getSelectedIndex()), MetodoDePagoComboBox.getItemAt(MetodoDePagoComboBox.getSelectedIndex()));
            listaAlquiler.add(newalquiler);
            MostrarInfor(listaAlquiler);
        }
        if (nArrendador.getText().isBlank()) {
            nArrendador.setBorder(new LineBorder(SystemColor.red));
        } else {
            nArrendador.setBorder(new LineBorder(SystemColor.black));
        }
        if (cArrendador.getText().isBlank()) {
            cArrendador.setBorder(new LineBorder(SystemColor.red));
        } else {
            cArrendador.setBorder(new LineBorder(SystemColor.black));
        }
        if (dcArrendador.getText().isBlank()) {
            dcArrendador.setBorder(new LineBorder(SystemColor.red));
        } else {
            dcArrendador.setBorder(new LineBorder(SystemColor.black));
        }
        if (plVehiculo.getText().isBlank()) {
            plVehiculo.setBorder(new LineBorder(SystemColor.red));
        } else {
            plVehiculo.setBorder(new LineBorder(SystemColor.black));
        }
        if (nArrendatario.getText().isBlank()) {
            nArrendatario.setBorder(new LineBorder(SystemColor.red));
        } else {
            nArrendatario.setBorder(new LineBorder(SystemColor.black));
        }
        if (cArrendatario.getText().isBlank()) {
            cArrendatario.setBorder(new LineBorder(SystemColor.red));
        } else {
            cArrendatario.setBorder(new LineBorder(SystemColor.black));
        }

    }//GEN-LAST:event_BotonRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonRegistrar;
    private javax.swing.JComboBox<String> MetodoDePagoComboBox;
    private javax.swing.JComboBox<String> TiempoContratoComboBox;
    private javax.swing.JTextField cArrendador;
    private javax.swing.JTextField cArrendatario;
    private javax.swing.JTextField dcArrendador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nArrendador;
    private javax.swing.JTextField nArrendatario;
    private javax.swing.JTextField plVehiculo;
    private javax.swing.JTable tableListaAlquiler;
    // End of variables declaration//GEN-END:variables
}
